apiVersion: v1
kind: Service
metadata:
  name: random-bot
  namespace: default
  labels:
    app: random-bot
spec:
  selector:
    app: random-bot
  ports:
  - name: http
    port: 80
    targetPort: 5000
