apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/goncharukinna/bots-gitops.git'
    targetRevision: HEAD
    path: manifests/cat-bot
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
